version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "America/Sao_Paulo"
    versioning-strategy: increase
