version: "3.8"
services:
  postgres-tempdb:
    image: postgres
    container_name: postgres-tempdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tempdb
      - POSTGRES_DB=tempdb
    ports:
      - "5432:5432"
    volumes:
      - tempdbPostgres:/data/postgres
  tempdb-server:
    build: .
    environment:
      - POSTGRES_DATABASE_URL=postgres://postgres:tempdb@postgres-tempdb:5432/tempdb
      - REDIS_APP_URL=redis://app-redis:6379
    links:
      - postgres-tempdb
      - app-redis
    depends_on:
      - postgres-tempdb
      - app-redis
    container_name: tempdb-server
    ports:
      - "5676:5676"
    volumes:
      - .:/app
  app-redis:
    image: redis
    container_name: app-redis
    restart: always
volumes:
  tempdbPostgres:
