version: "3.8"
services:
  postgres-tempdb:
    image: postgres
    container_name: postgres-tempdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tempdb
      - POSTGRES_DB=tempdb
    ports:
      - "5432:5432"
    volumes:
      - tempdbPostgres:/data/postgres
  tempdb-server:
    build: .
    environment:
      - POSTGRES_DATABASE_URL=postgres://postgres:tempdb@postgres-tempdb:5432/tempdb
    links:
      - postgres-tempdb
      - tempdb-redis
    depends_on:
      - postgres-tempdb
      - tempdb-redis
    container_name: tempdb-server
    ports:
      - "5676:5676"

volumes:
  tempdbPostgres:
